[package]
name = "mini_rbmq_server"
version = "0.1.0"
authors = ["MwlLj <731025894@qq.com>"]
edition = "2018"

[dependencies]
sqlite3 = "*"
rand = "*"
uuid = { version = "0.7", default-features = false, features = ["serde", "v4"] }
